import "@/style/style.scss";
import type { Metadata } from "next";
import { Providers } from "./providers";
import Nav from "@/components/common/navbar/nav"
import { Suspense } from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body>
                <Providers>
                    <Suspense>
                        <Nav  />
                    </Suspense>
                    {children}
                </Providers>
            </body>
        </html>
    );
}
